"""The GeoCell: a deformable geometric memory object with a belief lifecycle."""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

# Trinary relation states between cells.
SUPPORT = 1
UNKNOWN = 0
CONTRADICTION = -1

# Belief lifecycle states of a cell.
ACTIVE = "active"          # currently believed
CONTESTED = "contested"    # in unresolved contradiction
SUPERSEDED = "superseded"  # displaced by a newer/stronger claim; kept as history
RETRACTED = "retracted"    # a hypothesis defeated by observed evidence

# Provenance kinds.
OBSERVED = "observed"      # ingested from outside
INFERRED = "inferred"      # generated by the inference engine
CONCEPT = "concept"        # created by consolidation over a cluster


@dataclass
class GeoCell:
    id: int
    content: str
    position: List[float]
    radius: float
    created_at: float
    source: str
    date: str
    confidence: float
    authority: float
    subject: str
    values: List[Dict[str, Any]]
    polarity: int
    revision_signal: bool
    kind: str = OBSERVED
    status: str = ACTIVE
    trust: float = 0.5
    parents: List[int] = field(default_factory=list)
    ledger: List[str] = field(default_factory=list)

    def log(self, event: str) -> None:
        """Append to the cell's epistemic ledger: a human-readable audit
        trail of everything that ever happened to this belief."""
        self.ledger.append(f"{time.strftime('%Y-%m-%dT%H:%M:%S')} {event}")

    def view(self, score: Optional[float] = None) -> Dict[str, Any]:
        out = {
            "id": self.id,
            "content": self.content,
            "kind": self.kind,
            "status": self.status,
            "trust": round(self.trust, 4),
            "source": self.source,
            "date": self.date,
            "confidence": self.confidence,
            "authority": self.authority,
            "subject": self.subject,
            "values": self.values,
            "radius": round(self.radius, 4),
            "revision_signal": self.revision_signal,
            "parents": self.parents,
        }
        if score is not None:
            out["resonance"] = round(float(score), 4)
        return out
